package yahoofinance.quotes.query1v7;

public enum QuoteFields {
   symbol,
   longName,
   shortName,
   currency,
   fullExchangeName,
   regularMarketPrice,
   lastTradeSize,
   ask,
   askSize,
   bid,
   bidSize,
   regularMarketOpen,
   regularMarketPreviousClose,
   regularMarketDayHigh,
   regularMarketDayLow,
   exchangeTimezoneName,
   regularMarketTime,
   fiftyTwoWeekHigh,
   fiftyTwoWeekLow,
   fiftyDayAverage,
   twoHundredDayAverage,
   regularMarketVolume,
   averageDailyVolume3Month,
   marketCap,
   sharesOutstanding,
   epsTrailingTwelveMonths,
   trailingPE,
   epsForward,
   priceToBook,
   priceToSales,
   bookValue,
   ebitda,
   revenue
}
